name: movieverse
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  google_sign_in: ^6.2.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Network
  http: ^1.2.2
  connectivity_plus: ^6.0.5

  # UI & Media
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  video_player: ^2.9.1
  chewie: ^1.8.5
  youtube_player_flutter: ^9.0.1
  url_launcher: ^6.3.0

  # Icons
  cupertino_icons: ^1.0.8
  
  # Utils
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
